name: Chrome
on: push
jobs:
  chrome:
    runs-on: ubuntu-24.04
    name: E2E on Chrome
    steps:
      - uses: actions/checkout@v6
      - uses: cypress-io/github-action@v7
        with:
          browser: chrome
        env: 
            CYPRESS_STANDART_USER: ${{secrets.CYPRESS_STANDART_USER}}
            CYPRESS_LOCKED_USER: ${{secrets.CYPRESS_LOCKED_USER}}
            CYPRESS_PROBLEM_USER: ${{secrets.CYPRESS_PROBLEM_USER}}
            CYPRESS_PERFORMACEG_USER: ${{secrets.CYPRESS_PERFORMACEG_USER}}
            CYPRESS_ERRO_USER: ${{secrets.CYPRESS_ERRO_USER}}
            CYPRESS_VISUAL_USER: ${{secrets.CYPRESS_VISUAL_USER}}
            CYPRESS_PASS: ${{secrets.CYPRESS_PASS}}
            CYPRESS_URL: ${{secrets.CYPRESS_URL}}

      - uses: actions/upload-artifact@v6
        with:
          name: cypress-reports
          path: cypress/reports
          if-no-files-found: ignore
      